### ISSUE TITLE
[Data catalog] Add generic test for confirming hardcoded values

### ISSUE THREAD

**Issue by jeancochrane** [ccao-data/data-architecture#121]
Some of the reporting tests outlined in https://github.com/ccao-data/data-architecture/issues/95 require confirming that hardcoded values remain the same. To do this, we'll want to add a generic test that can take in input columns and values and confirm that a given set of columns in the result set contain the correct transformed values.

TODO: Some design from @jeancochrane on what this generic function should look like.

**Comment by jeancochrane** [comment]
@wagnerlmichael I think we can actually write this kind of test using `expression_is_true` without requiring a new generic test! For example, here's how we might add a test to `vw_assessment_roll` to confirm that the row with `stage: 'foo'` and `township_name: 'bar'` and `triad: 'baz'` has the values `bldg_sum: 10` and `bldg_median: 100`:

```yaml
models:
  - name: reporting.vw_assessment_roll
    tests:
      - expression_is_true:
          name: vw_assessment_roll_hardcoded_values
          expression: "bldg_sum = 10 and bldg_median = 100"
          select_columns:
            - stage
            - township_name
            - triad
          config:
            where: "stage = 'foo' and township_name = 'bar' and triad = 'baz'"
```

Does this seem reasonable to you? Happy to talk through what's going on here if it'd help 👍
